FROM quay.io/bitnami/wildfly:23.0.2-debian-10-r25 as wildfly

ARG KEYCLOAK_VERSION=15.0.2
FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

# Adds smallrye components that we're removed in Keycloak 13.0.1

# Add smallrye common
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/io/smallrye/common /opt/jboss/keycloak/modules/system/layers/base/io/smallrye/common

# Add smallrye config
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/io/smallrye/config /opt/jboss/keycloak/modules/system/layers/base/io/smallrye/config
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/org/eclipse/microprofile/config /opt/jboss/keycloak/modules/system/layers/base/org/eclipse/microprofile/config
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/org/wildfly/extension/microprofile/config-smallrye /opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/microprofile/config-smallrye

# Add smallrye health
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/io/smallrye/health /opt/jboss/keycloak/modules/system/layers/base/io/smallrye/health
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/org/eclipse/microprofile/health /opt/jboss/keycloak/modules/system/layers/base/org/eclipse/microprofile/health
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/org/wildfly/extension/microprofile/health-smallrye /opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/microprofile/health-smallrye

# Add smallrye metrics
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/io/smallrye/metrics /opt/jboss/keycloak/modules/system/layers/base/io/smallrye/metrics
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/org/eclipse/microprofile/metrics /opt/jboss/keycloak/modules/system/layers/base/org/eclipse/microprofile/metrics
COPY --from=wildfly --chown=1000:1000 /opt/bitnami/wildfly/modules/system/layers/base/org/wildfly/extension/microprofile/metrics-smallrye /opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/microprofile/metrics-smallrye

# Note that we need to register the smallrye components via 0010-register-smallrye-extensions.cli

USER jboss

# Add custom Startup-Scripts
COPY --chown=jboss:root maven/cli/ /opt/jboss/startup-scripts

# Add feature configuration
COPY --chown=jboss:root maven/config/ /opt/jboss/keycloak/standalone/configuration/

# Add Keycloak Extensions
COPY --chown=jboss:root maven/extensions/ /opt/jboss/keycloak/standalone/deployments

# Add custom Theme
COPY --chown=jboss:root maven/themes/apps/ /opt/jboss/keycloak/themes/apps
COPY --chown=jboss:root maven/themes/internal/ /opt/jboss/keycloak/themes/internal
